# ./docker-compose.yml
version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:80"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=myapi;Username=postgres;Password=postgres

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapi

volumes:
  postgres_data:
