services:
  compose-dashboard:
    container_name: "compose-dashboard"
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888:18888"  # Dashboard UI
      - "18889:18889"  # OTLP/gRPC endpoint
    environment:
      ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"  # Disable auth for dev
    networks:
      - "aspire"
    restart: "always"
  
  cache:
    image: "docker.io/library/redis:7-alpine"
    container_name: "redis-cache"
    command:
      - "-c"
      - "redis-server --requirepass $$REDIS_PASSWORD"
    entrypoint:
      - "/bin/sh"
    environment:
      REDIS_PASSWORD: "${CACHE_PASSWORD}"
    expose:
      - "6379"
    networks:
      - "aspire"
  
  postgres:
    image: "docker.io/library/postgres:15-alpine"
    container_name: "postgres"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "hodler-db"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "hodler-db-vol"
        read_only: false
    networks:
      - "aspire"
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hodler-db"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  hodler-api:
    image: "${HODLER_API_IMAGE}"
    container_name: "hodler-api"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${HODLER_API_PORT}"
      ConnectionStrings__hodler-db: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=hodler-db"
      ConnectionStrings__cache: "cache:6379,password=${CACHE_PASSWORD}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "hodler-api"
    ports:
      - "${HODLER_API_PORT}:${HODLER_API_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - "aspire"

networks:
  aspire:
    driver: "bridge"

volumes:
  hodler-db-vol:
    driver: "local"
