// <auto-generated />
using System;
using Hodler.Integration.Repositories.Portfolios.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hodler.Integration.Repositories.Migrations.Portfolio
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20250611192153_AddWalletAvatar")]
    partial class AddWalletAvatar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hodler.Integration.Repositories.Portfolios.Entities.BitcoinWallet", b =>
                {
                    b.Property<Guid>("BitcoinWalletId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvatarIcon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("ConnectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastSynced")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Network")
                        .HasColumnType("integer");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("WalletName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BitcoinWalletId");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("PortfolioId");

                    b.ToTable("BitcoinWallets");
                });

            modelBuilder.Entity("Hodler.Integration.Repositories.Portfolios.Entities.BlockchainTransaction", b =>
                {
                    b.Property<string>("TransactionHash")
                        .HasColumnType("text");

                    b.Property<Guid>("BitcoinWalletId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BtcAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FiatValueInUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MarketPriceInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetworkFeeInBtc")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetworkFeeInUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionHash");

                    b.HasIndex("BitcoinWalletId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("Timestamp", "Type", "FiatValueInUsd", "BtcAmount", "FromAddress", "ToAddress", "Status");

                    b.ToTable("BlockchainTransactions");
                });

            modelBuilder.Entity("Hodler.Integration.Repositories.Portfolios.Entities.ManualTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("BtcAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FiatAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("FiatCurrency")
                        .HasColumnType("integer");

                    b.Property<decimal>("MarketPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<int?>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("Timestamp", "PortfolioId", "Type", "FiatAmount", "BtcAmount");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Hodler.Integration.Repositories.Portfolios.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PortfolioId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Hodler.Integration.Repositories.Portfolios.Entities.BitcoinWallet", b =>
                {
                    b.HasOne("Hodler.Integration.Repositories.Portfolios.Entities.Portfolio", "Portfolio")
                        .WithMany("BitcoinWallets")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Hodler.Integration.Repositories.Portfolios.Entities.BlockchainTransaction", b =>
                {
                    b.HasOne("Hodler.Integration.Repositories.Portfolios.Entities.BitcoinWallet", "BitcoinWallet")
                        .WithMany("BlockchainTransactions")
                        .HasForeignKey("BitcoinWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hodler.Integration.Repositories.Portfolios.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BitcoinWallet");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Hodler.Integration.Repositories.Portfolios.Entities.ManualTransaction", b =>
                {
                    b.HasOne("Hodler.Integration.Repositories.Portfolios.Entities.Portfolio", "Portfolio")
                        .WithMany("ManualTransactions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Hodler.Integration.Repositories.Portfolios.Entities.BitcoinWallet", b =>
                {
                    b.Navigation("BlockchainTransactions");
                });

            modelBuilder.Entity("Hodler.Integration.Repositories.Portfolios.Entities.Portfolio", b =>
                {
                    b.Navigation("BitcoinWallets");

                    b.Navigation("ManualTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
