name: Deploy iOS to App Store

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build-and-upload:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      - name: Build iOS
        run: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

      - name: Upload to App Store
        uses: apple-actions/upload-testflight-build@v1
        with:
          appPath: build/ios/ipa/*.ipa
          apiKeyId: ${{ secrets.APPSTORE_API_KEY_ID }}
          apiKeyIssuer: ${{ secrets.APPSTORE_API_ISSUER }}
          apiKeyContent: ${{ secrets.APPSTORE_API_CONTENT }}
